### ISSUE TITLE
Discord.py possible bug

### ISSUE THREAD

**Issue by mjpikat** [Markanito/VATSIM-Discord-Bot#3]
On METAR and TAF command call, the following error is displayed:

```
Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/.local/lib/python3.8/site-packages/discord/client.py", line 351, in _run_event await coro(*args, **kwargs)
  File "bot.py", line 190, in on_command_error raise exc.original
  File "/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 167, in wrapped ret = await coro(*args, **kwargs)
  File "/vacc-bot/cogs/metar.py", line 110, in metar icon_url=ctx.author.avatar_url
AttributeError: 'Member' object has no attribute 'avatar_url'
```

By replacing `avatar_url` to `avatar.url`, another error appears:
```
AttributeError: 'NoneType' object has no attribute 'url'
```

**Comment by mjpikat** [comment]
Resolved by running the script with `sudo` or directly from a root account
